export type Product = {
    id: number,
    name: string,
    price: number,
    category_Id: number,
    weight: number,
    description_short: string,
    description: string,
    information: string,
    color: string,
    discount: number,
    availability: boolean,
    main_Image_Url: string,
    images_urls: string[],
    is_Featured: boolean,
    count: number,
    is_latest: boolean,
    review_count: number,
}